# Preprocessing

In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
from ydata_profiling import ProfileReport
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("D:/ML projects/Project_1(Customer Segmentation)/Data/raw/online_retail.csv")

# Handling Duplicate values

In [4]:
df.duplicated().sum()

np.int64(5268)

In [5]:
duplicates = df[df.duplicated()]
duplicates.head()

# Here we can see that not all duplicates are not actual duplicates because it’s a transactional structure
# In datasets like Online Retail Dataset, this pattern is common:
# Same InvoiceNo
# Same CustomerID
# Same Country
# BUT different StockCode, Description
# One invoice = multiple products purchased in a single transaction

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [6]:
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom

In [7]:
df_unique = df.drop_duplicates()

In [8]:
df_unique

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [9]:
df_536409 = df_unique[df_unique["InvoiceNo"] == "536409"]
df_536409

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
483,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,3,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
484,536409,21479,WHITE SKULL HOT WATER BOTTLE,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
486,536409,22785,SQUARECUSHION COVER PINK UNION FLAG,1,2010-12-01 11:45:00,6.75,17908.0,United Kingdom
487,536409,22975,SPACEBOY CHILDRENS EGG CUP,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
488,536409,22972,CHILDREN'S SPACEBOY MUG,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
490,536409,22568,FELTCRAFT CUSHION OWL,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
491,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
492,536409,22664,TOY TIDY DOLLY GIRL DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
493,536409,21609,SET 12 LAVENDER BOTANICAL T-LIGHTS,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
495,536409,20669,RED HEART LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
496,536409,90129F,RED GLASS TASSLE BAG CHARM,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
497,536409,90210B,CLEAR ACRYLIC FACETED BANGLE,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
498,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,1,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
499,536409,21955,DOORMAT UNION JACK GUNS AND ROSES,1,2010-12-01 11:45:00,7.95,17908.0,United Kingdom
500,536409,72802C,VANILLA SCENT CANDLE JEWELLED BOX,1,2010-12-01 11:45:00,4.25,17908.0,United Kingdom
501,536409,22109,FULL ENGLISH BREAKFAST PLATE,1,2010-12-01 11:45:00,3.75,17908.0,United Kingdom
502,536409,85116,BLACK CANDELABRA T-LIGHT HOLDER,5,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
503,536409,22531,MAGIC DRAWING SLATE CIRCUS PARADE,1,2010-12-01 11:45:00,0.42,17908.0,United Kingdom
504,536409,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
505,536409,22183,CAKE STAND VICTORIAN FILIGREE MED,1,2010-12-01 11:45:00,6.75,17908.0,United Kingdom
506,536409,21678,PAISLEY PATTERN STICKERS,6,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
507,536409,21676,FLOWERS STICKERS,6,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
508,536409,84625A,PINK NEW BAROQUECANDLESTICK CANDLE,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
509,536409,84625C,BLUE NEW BAROQUE CANDLESTICK CANDLE,3,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
510,536409,21931,JUMBO STORAGE BAG SUKI,2,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
511,536409,85169B,BLACK LOVE BIRD CANDLE,12,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
512,536409,16238,PARTY TIME PENCIL ERASERS,28,2010-12-01 11:45:00,0.21,17908.0,United Kingdom
513,536409,20668,DISCO BALL CHRISTMAS DECORATION,24,2010-12-01 11:45:00,0.12,17908.0,United Kingdom
514,536409,84906,PINK B'FLY C/COVER W BOBBLES,1,2010-12-01 11:45:00,5.95,17908.0,United Kingdom
515,536409,21867,PINK UNION JACK LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
516,536409,22075,6 RIBBONS ELEGANT CHRISTMAS,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
518,536409,21326,AGED GLASS SILVER T-LIGHT HOLDER,12,2010-12-01 11:45:00,0.65,17908.0,United Kingdom
519,536409,21065,BOOM BOX SPEAKER GIRLS,1,2010-12-01 11:45:00,5.95,17908.0,United Kingdom
520,536409,22074,6 RIBBONS SHIMMERING PINKS,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
522,536409,20713,JUMBO BAG OWLS,1,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
523,536409,20966,SANDWICH BATH SPONGE,2,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
524,536409,21116,OWL DOORSTOP,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
525,536409,90199C,5 STRAND GLASS NECKLACE CRYSTAL,2,2010-12-01 11:45:00,6.35,17908.0,United Kingdom
526,536409,22633,HAND WARMER UNION JACK,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
528,536409,22198,LARGE POPCORN HOLDER,1,2010-12-01 11:45:00,1.65,17908.0,United Kingdom
529,536409,21824,PAINTED METAL STAR WITH HOLLY BELLS,3,2010-12-01 11:45:00,1.45,17908.0,United Kingdom
530,536409,21823,PAINTED METAL HEART WITH HOLLY BELL,3,2010-12-01 11:45:00,1.45,17908.0,United Kingdom
531,536409,22153,ANGEL DECORATION STARS ON DRESS,6,2010-12-01 11:45:00,0.42,17908.0,United Kingdom
532,536409,22197,SMALL POPCORN HOLDER,2,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
533,536409,85099B,JUMBO BAG RED RETROSPOT,2,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
534,536409,85099F,JUMBO BAG STRAWBERRY,1,2010-12-01 11:45:00,1.95,17908.0,United Kingdom
535,536409,20717,STRAWBERRY SHOPPER BAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
536,536409,20723,STRAWBERRY CHARLOTTE BAG,1,2010-12-01 11:45:00,0.85,17908.0,United Kingdom
538,536409,21980,PACK OF 12 RED RETROSPOT TISSUES,12,2010-12-01 11:45:00,0.29,17908.0,United Kingdom
540,536409,22112,CHOCOLATE HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom

In [10]:
before = df.shape[0]
df = df.drop_duplicates()
after = df_unique.shape[0]

print(f"Removed {before - after} duplicate rows")

Removed 5268 duplicate rows

# Handling Missing Values

In [16]:
# Quantify Missingness Per Column
missing_percent = df_unique.isnull().mean() * 100
missing_percent.sort_values(ascending=False)

CustomerID     25.163377
InvoiceNo       0.000000
StockCode       0.000000
Description     0.000000
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
Country         0.000000
dtype: float64

In [17]:
df_unique['Description'] = df_unique['Description'].fillna('Unknown')

In [18]:
df_unique['CustomerID'].isnull().sum()

np.int64(135037)

In [19]:
df_unique_no_miss = df_unique[df_unique['CustomerID'].notna()]
df_unique_no_miss['CustomerID'] = df_unique_no_miss['CustomerID'].astype(int).astype(str)

In [20]:
# Verify Final Result
df_unique_no_miss['CustomerID'].isnull().sum()

np.int64(0)

# fixing datatypes

In [21]:
df_unique_no_miss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  object
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  object
 7   Country      401604 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 27.6+ MB

In [22]:
df_unique_no_miss['InvoiceDate'] = pd.to_datetime(df_unique_no_miss['InvoiceDate'])

# Checking if everything is okay

In [23]:
df_unique_no_miss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  object
 7   Country      401604 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.6+ MB

In [24]:
profile = ProfileReport(df_unique_no_miss, title="Profiling Report 2")
profile.to_file("Cleaned report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.46it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
df_2o = df_unique_no_miss.copy()
df_2o

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [28]:
# Exporting the cleaned file
df_2o.to_csv('D:/ML projects/Project_1(Customer Segmentation)/Data/processed/output.csv', index=False)